apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.attributeServiceConfig.name }}
  labels:
    release: {{ .Release.Name }}
data:
  application.conf: |-
    document.store {
      {{- $dst := .Values.attributeServiceConfig.dataStoreType }}
      dataStoreType = {{ $dst }}
      {{ $dst }} {
        {{- range $key, $value := (index .Values "attributeServiceConfig" (printf "%s" $dst)) }}
        {{- if $value }}
        {{ $key }} = {{ $value | quote }}
        {{- end }}
        {{- end }}
      }
    }
