###########
# Deployment and Service
###########
replicaCount: 1
maxUnavailable: 0

image:
  repository: hypertrace/hypertrace
  pullPolicy: IfNotPresent
  tagOverride: ""

imagePullSecrets: []

containerPort: 9001
containerHealthProbePort: 9002
graphqlPort: 23431

nodeLabels: {}

javaOpts: "-XX:InitialRAMPercentage=50.0 -XX:MaxRAMPercentage=75.0"

livenessProbe:
  initialDelaySeconds: 10
  periodSeconds: 5

readinessProbe:
  initialDelaySeconds: 2
  periodSeconds: 5

resources:
  limits:
    cpu: 2
    memory: 768Mi
  requests:
    cpu: 100m
    memory: 768Mi

deploymentLabels:
  app: hypertrace

podLabels:
  app: hypertrace

deploymentSelectorMatchLabels:
  app: hypertrace

logConfig:
  name: hypertrace-log-config
  monitorInterval: 30
  rootLogger:
    level: ERROR
  appender:
    rolling:
      enabled: false
  loggers:
    loggers:
      - HYPERTRACE
    HYPERTRACE:
      name: org.hypertrace
      level: INFO
