apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.hypertraceDataQueryServiceConfig.name }}
  labels:
    release: {{ .Release.Name }}
data:
  {{- toYaml .Values.hypertraceDataQueryServiceConfig.data | nindent 2 }}