apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    release: {{ .Release.Name }}s
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: grpc-port
      name: grpc-8090
  selector:
    {{- toYaml .Values.serviceSelectorLabels | nindent 4 }}
